site_name: HeyTeam Documentation
nav:
  - Documentation: 'about.md'
  - Accueil: 'index.md'
  - Organisation du code: 'CodeOrganization.md'
  - Utilisation de l'architecture Page Object: 'PageObjectArchitecture.md'
  - Gestion des données de test: 'TestDataManagement.md'
  - Configuration et gestion des environnements: 'EnvironmentConfigManagement.md'
  - Utilisation des assertions: 'AssertionsUsage.md'
  - Gestion des dépendances: 'DependenciesManagement.md'
  - Rapports et Journaux détaillés: 'DetailedReportsLogs.md'
  - Gestion des dépendances réseau: 'NetworkDependenciesManagement.md'
  - Exécution des tests: 'RunningTests.md'
  - CI/CD exécution des tests: 'GitHubActions.md'
  - Analyse du code et bonnes pratiques: 'LoginTestDetails.md'
  - Utilisation des scripts: 'project-info-doc.md'
  - Utilisation des scripts suite: 'Script-checkDependencies-doc.md'
  - Configuration du débogage Playwright: 'DebugPlaywright.md'
  - Test management: 'test-management.md'
theme: readthedocs
