name: Manual trigger workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test

      - name: Archive test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: ./allure-results

  deploy_mkdocs:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install mkdocs
      - run: mkdocs build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./projectDocs/site
          publish_branch: gh-pages
          destination_dir: docs
      - run: |
          sed -i 's#(https://eliottealderson.github.io/QA-test-case-interview/#(https://eliottealderson.github.io/QA-test-case-interview/docs#' README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update README with new Mkdocs link" -a
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: 'main'
      - name: Post the link to the documentation
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.DEPLOY_TOKEN }}
          context: 'Documentation'
          state: 'success'
          sha: ${{ github.sha }}
          target_url: https://eliottealderson.github.io/QA-test-case-interview/docs
      - name: Install nodemailer
        run: npm install nodemailer
      - name: Send email notification
        run: node ./scripts/send_email_notification.mjs
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}

  deploy_allure:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: allure-results

      - name: Generate Allure Report and Publish
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: allure-results
          gh_pages: true

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          destination_dir: allure
      - run: |
          sed -i 's#(https://eliottealderson.github.io/QA-test-case-interview/#(https://eliottealderson.github.io/QA-test-case-interview/allure#' README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update README with new Allure link" -a
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: 'main'
      - name: Post the link to the Allure report
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.DEPLOY_TOKEN }}
          context: 'Allure Report'
          state: 'success'
          sha: ${{ github.sha }}
          target_url: https://eliottealderson.github.io/QA-test-case-interview/allure
      - name: Install nodemailer
        run: npm install nodemailer
      - name: Send email notification
        run: node ./scripts/send_email_notification.mjs
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}