name: Manual trigger workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: List project directory after tests
        run: ls -l

      - name: "Debug: List files in test-results"
        run: ls -R ./test-results

      - name: "Debug: List all files"
        run: ls -R

      - name: Install Allure commandline
        run: |
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
          tar -zxvf allure-commandline-2.13.8.tgz
          echo "${PWD}/allure-2.13.8/bin" >> $GITHUB_PATH

      - name: Generate Allure report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Archive test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            ./test-results
            ./allure-report