name: Manual trigger workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm cache clean --force && npm ci
      - name: Install @playwright/test
        run: npm install -D @playwright/test
      - name: Run tests
        run: npx playwright test
      - name: Archive test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            ./artifacts/
