name: Manual trigger workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: List project directory after tests
        if: ${{ always() }}
        run: ls -l

      - name: "Debug: List files in test-results"
        if: ${{ always() }}
        run: ls -R ./test-results

      - name: "Debug: List all files"
        if: ${{ always() }}
        run: ls -R

      - name: Generate Allure report and Publish
        if: ${{ always() }}
        uses: afiore/action-allure-report@v0.1.0
        with:
          results-dir: ./allure-results
          report-dir: ./allure-report

      - name: Archive test artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            ./test-results
            ./allure-report