name: Manual trigger workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test

      - name: Archive test artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: ./allure-results

  deploy_mkdocs:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install mkdocs
      - run: mkdocs build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./projectDocs/site
          publish_branch: gh-pages
          destination_dir: docs
      - run: |
          sed -i 's#(https://eliottealderson.github.io/QA-test-case-interview/\(.*[^/]\)#(https://eliottealderson.github.io/QA-test-case-interview/\1/docs#' README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update README with new Mkdocs link" -a
        if: ${{ always() }}
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: 'main'
        if: ${{ always() }}

      - name: Post the link to the documentation
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.DEPLOY_TOKEN }}
          context: 'Documentation'
          state: 'success'
          sha: ${{ github.sha }}
          target_url: https://eliottealderson.github.io/QA-test-case-interview/docs
      - name: Install nodemailer
        run: npm install nodemailer
      - name: Send email notification
        run: node ./scripts/send_email_notification.mjs
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}

  deploy_allure:
    needs: [ build, deploy_mkdocs ]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        with:
          name: allure-results

      - name: List files in current directory after download
        run: |
          echo "List of files in current directory after download:"
          ls -la

      - name: Move Allure results to allure/allure-results directory
        run: |
          mkdir -p allure/allure-results
          for file in *.json; do
            if [ "$file" != "jsdoc.json" ] && [ "$file" != "package-lock.json" ] && [ "$file" != "package.json" ]; then
              mv "$file" allure/allure-results/
            fi
          done
          mv *.txt allure/allure-results/
          echo "List of files in allure/allure-results directory:"
          ls -la allure/allure-results

      - name: Checkout gh-pages and deploy Allure Report
        run: |
          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add allure
          git commit -m "Add allure-results to allure directory"
          git push origin gh-pages    
      
      - name: Verify working directory
        run: |
          pwd
          ls
  
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Update README
        run: |
          git pull origin main
          sed -i 's#(https://eliottealderson.github.io/QA-test-case-interview/\(.*[^/]\)#(https://eliottealderson.github.io/QA-test-case-interview/\1/allure#' README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update README with new Allure link" -a
        if: ${{ always() }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: 'main'
        if: ${{ always() }}
          
      - name: Post the link to the Allure report
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.DEPLOY_TOKEN }}
          context: 'Allure Report'
          state: 'success'
          sha: ${{ github.sha }}
          target_url: https://eliottealderson.github.io/QA-test-case-interview/allure
      - name: Install nodemailer
        run: npm install nodemailer
      - name: Send email notification
        run: node ./scripts/send_email_notification.mjs
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}