name: Manual trigger workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Copy Allure results
        if: ${{ always() }}
        run: |
          cp -r allure-results allure-results-copy

      - name: Archive Allure results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results-copy

      - name: List project directory after tests
        if: ${{ always() }}
        run: ls -l

      - name: "Debug: List files in test-results"
        if: ${{ always() }}
        run: ls -R ./test-results

      - name: "Debug: List all files"
        if: ${{ always() }}
        run: ls -R

  deploy_mkdocs:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Echo working directory
        run: echo $(pwd)

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_branch: docs
          publish_dir: ./projectDocs/site
          keep_files: true

      - name: Post the link to the documentation
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.DEPLOY_TOKEN }}
          context: 'Documentation'
          state: 'success'
          sha: ${{ github.sha }}
          target_url: https://eliottealderson.github.io/QA-test-case-interview/

      - name: Install nodemailer
        run: npm install nodemailer
      - name: Send email notification
        run: node ./scripts/send_email_notification.mjs
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}

  deploy_allure:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v2
        with:
          name: allure-results-copy

      - name: "Debug: List files after download"
        run: ls -R .

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report and Publish
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results-copy
          gh_pages: gh-pages
          allure_report: ./allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GH_PAT }}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.sha }}
          target_url: https://eliottealderson.github.io/QA-test-case-interview/${{ github.run_number }}

      - name: Archive test artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            ./test-results
            ./allure-report
